variable "env" {}
variable "subnet_ids" {}
variable "allow_cidr_blocks" {}
variable "vpc_id" {}
variable "component" {}
variable "port_number" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
variable "instance_type" {}
variable "bastion_cidr" {}
variable "alb" {}
variable "listener" {}
variable "priority" {}
variable "alb_arn" {}
#variable "monitor_cidr" {}